### PR TITLE
Accepts rails 4.2

### PR DESCRIPTION
**Pull request by eltonlk**

### CODE REVIEW

**Comment by felipediesel** [comment]
@tomas-stefano Could you merge this and update the gem? We are currently using this, but setting to use our github project.

Thanks

**Comment by tomas-stefano** [comment]
Yes, of course.

**Comment by tomas-stefano** [comment]
Version v0.0.2 released. If you need anything, please let me know. Cheers.

**Comment by felipediesel** [comment]
Thank you very much!

**Pull request merged**
