### PR TITLE
Adding Caixa, HSBC, Sicredi, Real, Sicoob to this gem.

### PR DESCRIPTION
**Pull request by felipediesel**
We are replacing brcobranca with this gem, so we add the supported gems from there.

This was implemented from documentations provided by banks.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
Cool! Excellent work. :+1: :+1:
But can you add documentation to the Readme?
Another thing, can you reword the commit that you wrote in portuguese, and writing in english? I know that the code is written in Portuguese, but I prefer the commit messages in english. 
After this two changes, everything good to :ship: :)

**Comment by felipediesel** [comment]
OK. I'll work on this.

**Comment by felipediesel** [comment]
We fixed both issues. Now is good to go.

**Comment by tomas-stefano** [comment]
Cool! Nice work, mate.

**Pull request merged**
