### PR TITLE
Homologação Santander

### PR DESCRIPTION
**Pull request by nathmisaki**
Santander working.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
@nelsonmhjr can you rebase this PR. I would like to get merged this one :) .

**Comment by tomas-stefano** [comment]
@nelsonmhjr can you rebase this PR or pair on the rebase? Wdyt?

**Comment by nathmisaki** [comment]
@tomas-stefano I just rebased, but it seems that some tests broke. I will fix them and update it, later this week.

**Comment by tomas-stefano** [comment]
Hi @nelsonmhjr sorry to ask, but did you fix the tests? I am happy to merge when the tests passes. :)

**Pull request closed without merging**
